/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netflix;

import com.mysql.jdbc.Connection;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author ozden
 */
public class izlemeekranı extends javax.swing.JFrame {

    /**
     * Creates new form izlemeekranı
     */
    Timer t;
    Connection conn;
    Statement st;
    ResultSet rs;

    public izlemeekranı() {
        initComponents();
        setIconImage();
        oynayanfilm.setText(anasayfa.izlenecekfilm);
        if (anasayfa.izlencektur.equals("Film")) {
            jLabel3.setVisible(false);
            bolumsec.setVisible(false);
        } else {
            for (int i = 1; i <= anasayfa.bolsayi; i++) {
                bolumsec.addItem(Integer.toString(i));
            }
        }
        bolumyukle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sure = new javax.swing.JLabel();
        oynayanfilm = new javax.swing.JLabel();
        durum = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        puanla = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        bolumsec = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        sure.setBackground(new java.awt.Color(0, 0, 0));
        sure.setForeground(new java.awt.Color(255, 255, 255));

        oynayanfilm.setBackground(new java.awt.Color(0, 0, 0));
        oynayanfilm.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        oynayanfilm.setForeground(new java.awt.Color(255, 255, 255));

        durum.setBackground(new java.awt.Color(0, 0, 0));
        durum.setForeground(new java.awt.Color(255, 255, 255));

        play.setBackground(new java.awt.Color(0, 0, 0));
        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        pause.setBackground(new java.awt.Color(0, 0, 0));
        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pause.png"))); // NOI18N
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        puanla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        puanla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puanlaActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("İzlemek istediğiniz bölümü seçin: ");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Bitir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bu programı oyla");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 23, Short.MAX_VALUE)
                                        .addComponent(durum, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sure, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oynayanfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bolumsec, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puanla, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bolumsec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(puanla)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oynayanfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pause, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(play, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sure, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(durum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
static int gecensaniye;
    static int gecendakika;
    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        durum.setText("Oynatılıyor");
        conn = Sqlbaglanti.getConnection();
        try {
            st = conn.createStatement();
            rs = st.executeQuery("select kaldıgıdk,kaldıgısn,mail,programadi FROM kullanici_program");
            while (rs.next()) {
                if (rs.getString("mail").equalsIgnoreCase(girisekrani.mail) && rs.getString("programadi").equalsIgnoreCase(anasayfa.izlenecekfilm)) {
                    gecendakika = rs.getInt("kaldıgıdk");
                    gecensaniye = rs.getInt("kaldıgısn");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(izlemeekranı.class.getName()).log(Level.SEVERE, null, ex);
        }

        t = new Timer(1000, (ActionEvent e) -> {
            if (gecensaniye > 59) {
                gecendakika++;
                gecensaniye /= 60;
                gecensaniye--;
            }
            sure.setText(String.valueOf(gecendakika) + ":" + String.valueOf(gecensaniye));
            gecensaniye++;
        });
        t.start();
    }//GEN-LAST:event_playActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        t.stop();
        durum.setText("Durduruldu");
    }//GEN-LAST:event_pauseActionPerformed
    static int verdigipuan;

    float oylamasayisi;
    public float yenipuan;
    private void puanlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puanlaActionPerformed
        verdigipuan = puanla.getSelectedIndex() + 1;

        conn = Sqlbaglanti.getConnection();
        try {
            st = conn.createStatement();
            rs = st.executeQuery("SELECT ad,puan,oylamasayisi FROM programlar");
            while (rs.next()) {
                if (rs.getString("ad").equalsIgnoreCase(anasayfa.izlenecekfilm)) {

                    oylamasayisi = rs.getFloat("oylamasayisi") + 1;
                    yenipuan = (rs.getFloat("puan") * rs.getFloat("oylamasayisi") + verdigipuan) / oylamasayisi;
                    Sqlbaglanti.ekle("UPDATE programlar SET oylamasayisi=" + oylamasayisi + " WHERE ad='" + anasayfa.izlenecekfilm + "'");
                    Sqlbaglanti.ekle("UPDATE programlar SET puan=" + yenipuan + " WHERE ad='" + anasayfa.izlenecekfilm + "'");
                    /*jLabel1.setVisible(false);
                     puanla.setVisible(false);*/
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(izlemeekranı.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_puanlaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        kul_turpuanekle(verdigipuan);
      //  new anasayfa().setVisible(true);
        //  setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line argumentsS
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(izlemeekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(izlemeekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(izlemeekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(izlemeekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new izlemeekranı().setVisible(true);
            }
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bolumsec;
    private javax.swing.JLabel durum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel oynayanfilm;
    private javax.swing.JButton pause;
    private javax.swing.JButton play;
    private javax.swing.JComboBox puanla;
    private javax.swing.JLabel sure;
    // End of variables declaration//GEN-END:variables

    int kont = 0;

    private void kul_turpuanekle(int puan) {
        boolean ctrl = false;
        try {
            conn = Sqlbaglanti.getConnection();
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM kullanici_program");

            while (rs.next()) {
                if (rs.getString("mail").equals(girisekrani.mail) && kont == 0) {
                    if (rs.getString("programadi").equals(anasayfa.izlenecekfilm)) {
                        ctrl = true;
                        Sqlbaglanti.ekle("UPDATE kullanici_program SET izlemetarihi='" + Sqlbaglanti.sistemTarihiniGetir("yyyy/MM/dd") + "' WHERE mail='" + girisekrani.mail + "'");
                        Sqlbaglanti.ekle("UPDATE kullanici_program SET kaldıgıdk=" + gecendakika + " WHERE mail='" + girisekrani.mail + "'");
                        Sqlbaglanti.ekle("UPDATE kullanici_program SET kaldıgısn=" + gecensaniye + " WHERE mail='" + girisekrani.mail + "'");
                        Sqlbaglanti.ekle("UPDATE kullanici_program SET kaldıgıbolum=" + (bolumsec.getSelectedIndex() + 1) + " WHERE mail='" + girisekrani.mail + "'");
                        Sqlbaglanti.ekle("UPDATE kullanici_program SET puan=" + puan + " WHERE mail='" + girisekrani.mail + "'");
                        Sqlbaglanti.ekle("UPDATE kullanici_program SET programadi='" + anasayfa.izlenecekfilm + "' WHERE mail='" + girisekrani.mail + "'");
                        //System.out.println("INSERT INTO kullanici_program (izlemetarihi,kaldıgıdk,kaldıgısn,kaldıgıbolum,puan,programadi,mail) VALUES ('"+Sqlbaglanti.sistemTarihiniGetir("yyyy/MM/dd")+"','"+gecendakika+"','"+gecensaniye+"','"+(bolumsec.getSelectedIndex()+1)+"','"+puan+"','"+anasayfa.izlenecekfilm+"','"+girisekrani.mail+"')");
                        kont++;
                    } else if (kont == 1) {
                        Sqlbaglanti.ekle("INSERT INTO kullanici_program (izlemetarihi,kaldıgıdk,kaldıgısn,kaldıgıbolum,puan,programadi,mail) VALUES ('" + Sqlbaglanti.sistemTarihiniGetir("yyyy/MM/dd") + "','" + gecendakika + "','" + gecensaniye + "','" + (bolumsec.getSelectedIndex() + 1) + "','" + puan + "','" + anasayfa.izlenecekfilm + "','" + girisekrani.mail + "')");
                    }

                }

            }

            if (ctrl == false) {
                Sqlbaglanti.ekle("INSERT INTO kullanici_program (izlemetarihi,kaldıgıdk,kaldıgısn,kaldıgıbolum,puan,programadi,mail) VALUES ('" + Sqlbaglanti.sistemTarihiniGetir("yyyy/MM/dd") + "','" + gecendakika + "','" + gecensaniye + "','" + (bolumsec.getSelectedIndex() + 1) + "','" + puan + "','" + anasayfa.izlenecekfilm + "','" + girisekrani.mail + "')");
            }
        } catch (SQLException ex) {
            Logger.getLogger(izlemeekranı.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void bolumyukle() {
        conn = Sqlbaglanti.getConnection();
        try {
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM kullanici_program");
            while (rs.next()) {
                if (rs.getString("mail").equalsIgnoreCase(girisekrani.mail) && rs.getString("programadi").equalsIgnoreCase(anasayfa.izlenecekfilm)) {
                    if (rs.getInt("kaldıgıbolum") != 0) {
                        jLabel4.setText(rs.getInt("kaldıgıbolum") + ". bölümde kalmıştınız.");
                    }
                    puanla.setSelectedIndex(rs.getInt("puan") - 1);

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(izlemeekranı.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
