package netflix;

import com.mysql.jdbc.Connection;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

public class kayitekrani extends javax.swing.JFrame {

    /**
     * Creates new form kayitekrani
     */
    public kayitekrani() {
        initComponents();
        setIconImage();

    }
    static String name;
    static String email;
    static String bday;
    static String pass;
    static String sql_sorgu;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sifre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dgunu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        uyari = new javax.swing.JLabel();
        stat = new javax.swing.JLabel();
        aksiyon = new javax.swing.JCheckBox();
        aksiyonvemacera = new javax.swing.JCheckBox();
        anime = new javax.swing.JCheckBox();
        belgesel = new javax.swing.JCheckBox();
        bilimkurgu = new javax.swing.JCheckBox();
        bilimkurguvefantastik = new javax.swing.JCheckBox();
        bilimvedoga = new javax.swing.JCheckBox();
        cocukveaile = new javax.swing.JCheckBox();
        drama = new javax.swing.JCheckBox();
        gerilim = new javax.swing.JCheckBox();
        komedi = new javax.swing.JCheckBox();
        korku = new javax.swing.JCheckBox();
        reality = new javax.swing.JCheckBox();
        romantik = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sevdiğiniz Türleri Seçin (3 Seçim Yapınız)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Adınız:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("E-Postanız:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Şifreniz:");

        dgunu.setText("yyyy-aa-gg");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Doğum Gününüz:");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kaydol!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        uyari.setForeground(new java.awt.Color(255, 255, 255));

        stat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stat.setForeground(new java.awt.Color(240, 240, 240));

        aksiyon.setBackground(new java.awt.Color(0, 0, 0));
        aksiyon.setForeground(new java.awt.Color(255, 255, 255));
        aksiyon.setText("Aksiyon");

        aksiyonvemacera.setBackground(new java.awt.Color(0, 0, 0));
        aksiyonvemacera.setForeground(new java.awt.Color(255, 255, 255));
        aksiyonvemacera.setText("Aksiyon ve Macera");

        anime.setBackground(new java.awt.Color(0, 0, 0));
        anime.setForeground(new java.awt.Color(255, 255, 255));
        anime.setText("Anime");

        belgesel.setBackground(new java.awt.Color(0, 0, 0));
        belgesel.setForeground(new java.awt.Color(255, 255, 255));
        belgesel.setText("Belgesel");

        bilimkurgu.setBackground(new java.awt.Color(0, 0, 0));
        bilimkurgu.setForeground(new java.awt.Color(255, 255, 255));
        bilimkurgu.setText("Bilim Kurgu");

        bilimkurguvefantastik.setBackground(new java.awt.Color(0, 0, 0));
        bilimkurguvefantastik.setForeground(new java.awt.Color(255, 255, 255));
        bilimkurguvefantastik.setText("Bilim Kurgu ve Fantastik Yapımlar");

        bilimvedoga.setBackground(new java.awt.Color(0, 0, 0));
        bilimvedoga.setForeground(new java.awt.Color(255, 255, 255));
        bilimvedoga.setText("Bilim ve Doğa");

        cocukveaile.setBackground(new java.awt.Color(0, 0, 0));
        cocukveaile.setForeground(new java.awt.Color(255, 255, 255));
        cocukveaile.setText("Çocuk ve Aile");

        drama.setBackground(new java.awt.Color(0, 0, 0));
        drama.setForeground(new java.awt.Color(255, 255, 255));
        drama.setText("Drama");

        gerilim.setBackground(new java.awt.Color(0, 0, 0));
        gerilim.setForeground(new java.awt.Color(255, 255, 255));
        gerilim.setText("Gerilim");

        komedi.setBackground(new java.awt.Color(0, 0, 0));
        komedi.setForeground(new java.awt.Color(255, 255, 255));
        komedi.setText("Komedi");

        korku.setBackground(new java.awt.Color(0, 0, 0));
        korku.setForeground(new java.awt.Color(255, 255, 255));
        korku.setText("Korku");

        reality.setBackground(new java.awt.Color(0, 0, 0));
        reality.setForeground(new java.awt.Color(255, 255, 255));
        reality.setText("Reality Program");

        romantik.setBackground(new java.awt.Color(0, 0, 0));
        romantik.setForeground(new java.awt.Color(255, 255, 255));
        romantik.setText("Romantik");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sevdiğiniz Türleri Seçin (3 Seçim Yapınız)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(uyari, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sifre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(dgunu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(aksiyon)
                                        .addGap(136, 136, 136))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(anime)
                                                    .addComponent(aksiyonvemacera))
                                                .addGap(66, 66, 66))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bilimkurguvefantastik)
                                                .addComponent(bilimkurgu)
                                                .addComponent(belgesel)
                                                .addComponent(bilimvedoga)))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cocukveaile)
                                    .addComponent(romantik)
                                    .addComponent(reality)
                                    .addComponent(korku)
                                    .addComponent(komedi)
                                    .addComponent(gerilim)
                                    .addComponent(drama)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(54, 54, 54))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dgunu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aksiyon)
                            .addComponent(cocukveaile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(aksiyonvemacera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(belgesel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bilimkurgu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bilimkurguvefantastik)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bilimvedoga))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(drama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gerilim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(komedi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(korku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reality)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(romantik)))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(uyari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection conn;
    Statement st;
    ResultSet rs;
    boolean a = true;
    String[] b = new String[3];
    int sayac = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        name = ad.getText();
        email = mail.getText();
        bday = dgunu.getText();
        pass = sifre.getText();
        if (aksiyon.isSelected() && sayac < 3) {
            b[sayac++] = "Aksiyon";
        }
        if (aksiyonvemacera.isSelected() && sayac < 3) {
            b[sayac++] = "Aksiyon ve Macera";
        }
        if (anime.isSelected() && sayac < 3) {
            b[sayac++] = "Anime";
        }
        if (belgesel.isSelected() && sayac < 3) {
            b[sayac++] = "Belgesel";
        }
        if (bilimkurgu.isSelected() && sayac < 3) {
            b[sayac++] = "Bilim Kurgu";
        }
        if (bilimkurguvefantastik.isSelected() && sayac < 3) {
            b[sayac++] = "Bilim Kurgu ve Fantastik Yapımlar";
        }
        if (bilimvedoga.isSelected() && sayac < 3) {
            b[sayac++] = "Bilim ve Doğa";
        }
        if (cocukveaile.isSelected() && sayac < 3) {
            b[sayac++] = "Çocuk ve Aile";
        }
        if (drama.isSelected() && sayac < 3) {
            b[sayac++] = "Drama";
        }
        if (gerilim.isSelected() && sayac < 3) {
            b[sayac++] = "Gerilim";
        }
        if (komedi.isSelected() && sayac < 3) {
            b[sayac++] = "Komedi";
        }
        if (korku.isSelected() && sayac < 3) {
            b[sayac++] = "Korku";
        }
        if (reality.isSelected() && sayac < 3) {
            b[sayac++] = "Reality Program";
        }
        if (romantik.isSelected() && sayac < 3) {
            b[sayac++] = "Romantik";
        }
        sql_sorgu = "INSERT INTO kullanici (isim,mail,sifre,d_gunu,sevdigi1,sevdigi2,sevdigi3) VALUES ('" + name
                + "','" + email + "','" + pass + "','" + bday + "','" + b[0] + "', '" + b[1] + "', '" + b[2] + "')";
        //System.out.println(sql_sorgu);
        conn = Sqlbaglanti.getConnection();
        try {
            st = conn.createStatement();
            rs = st.executeQuery("select * from kullanici");
            while (rs.next()) {
                if (email.equals(rs.getString("mail"))) {
                    stat.setText("E-posta adresi zaten kayıtlı !!");
                    ad.setText("");
                    mail.setText("");
                    dgunu.setText("");
                    sifre.setText("");
                    a = false;
                }
            }
            if (a == true) {
                Sqlbaglanti.ekle(sql_sorgu);
                setVisible(false);
                new girisekrani().setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(kayitekrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        Sqlbaglanti.closeConnection(conn);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayitekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayitekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayitekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayitekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayitekrani().setVisible(true);
            }
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JCheckBox aksiyon;
    private javax.swing.JCheckBox aksiyonvemacera;
    private javax.swing.JCheckBox anime;
    private javax.swing.JCheckBox belgesel;
    private javax.swing.JCheckBox bilimkurgu;
    private javax.swing.JCheckBox bilimkurguvefantastik;
    private javax.swing.JCheckBox bilimvedoga;
    private javax.swing.JCheckBox cocukveaile;
    private javax.swing.JTextField dgunu;
    private javax.swing.JCheckBox drama;
    private javax.swing.JCheckBox gerilim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox komedi;
    private javax.swing.JCheckBox korku;
    private javax.swing.JTextField mail;
    private javax.swing.JCheckBox reality;
    private javax.swing.JCheckBox romantik;
    private javax.swing.JTextField sifre;
    private javax.swing.JLabel stat;
    private javax.swing.JLabel uyari;
    // End of variables declaration//GEN-END:variables
}
